baseURL = "https://yannickschutz.com/"
languageCode = "en-us"
title = "Yannick Schutz"
theme = "term"
enableRobotsTXT = true
canonifyURLs = false
disableKinds = ["section", "taxonomy", "taxonomyTerm"]

[params]
  textFont = 'Source Code Pro'
  footer = '🌲 Please consider the environment before printing this website'

[params.social]
  email = "hello@yannickschutz.com"

[params.fathom]
  host = "logs.vadrouilles.co"
  siteID = "IMJQP"
